services:
  web:
    build: .
    ports:
      - "${PORT:-8501}:8501"
    env_file:
      - .env
    environment:
      - UV_PYTHON_PREFERENCE=system
    volumes:
      - ./:/app
      - venv:/app/.venv
      - uv_cache:/root/.cache/uv
    command: >
      sh -lc "uv sync &&
        uv run -- streamlit run src/app/app.py
        --server.address 0.0.0.0
        --server.port ${PORT:-8501}"

volumes:
  venv:
  uv_cache:
