services:
  web:
    build:
      context: .
      args:
        TORCH_CUDA: cu125
    network_mode: host
    env_file:
      - .env
    environment:
      - UV_LINK_MODE=copy
      - STREAMLIT_SERVER_RUN_ON_SAVE=false
      - STREAMLIT_SERVER_FILEWATCHERTYPE=none
    volumes:
      - ./:/app
      - venv:/app/.venv
      - uv_cache:/root/.cache/uv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  venv:
  uv_cache:
